### ISSUE TITLE
activityFinder Latches onto Incorrect Activity Instance

### ISSUE THREAD

**Issue by meganmjones** [NASA-AMMOS/aerie#1061] opened 2023-08-03 19:26 UTC
### Checked for duplicates

Yes - I've already checked

### Is this a regression?

No - This is a new bug

### Version

1.6.1

### Describe the bug

When trying to run multiple schedule goals - each placing several activities including GNC turns - that have the same base constraints (i.e. 1x occurrence in >2AU region) the activityFinder feature sometimes hooks activities onto one prior that does not match the exact parameter specifications laid out in the activityFinder's ActivityExpression.build section. 

In this exact example shown below, I ran two scheduling goals - TEL_HGA_Cruise_Cal and GNC_DSS_Boresight_Vectors_Cal. The TEL goal including a GNC_Single_Turn linked directly after the primary TEL activity to return to background pointing (-Y to **Earth**, -X to ECLIP2000_POSZ). The GNC DSS goal includes a GNC_Solar_Array_Single_Articulation and GNC_Single_Turn linked to end before the GNC DSS activity (-Y to **Sun**, -X to ECLIP2000_POSZ) as well as a GNC_Solar_Array_Sun_Track and GNC_Single_Turn linked to start at the end of the DSS activity to return to background pointing.

These two goals were run at the same time with TEL_HGA_Cruise_Cal highest priority and GNC_DSS_Cal second. As you can see, the GNC_Single_Turn that was setup after the TEL_HGA_Cruise_Cal has the GNC_Single_Turn parameters matching it's return turn. However, this turn is immediately prior to the GNC DSS activity (Generic_GNC_Hardware_State_Update) and does **not** match the GNC_Single_Turn parameters required for it's setup turn (as specified in the scheduling goal + activityFinder).
![Screenshot 2023-08-03 at 10 51 07 AM](https://github.com/NASA-AMMOS/aerie/assets/40210944/f88059fd-5f8e-4e15-8a15-a4ddf003b297)

Below is the result of running the TEL_HGA_Cruise_Cal goal in isolation:
![Screenshot 2023-08-03 at 9 49 42 AM](https://github.com/NASA-AMMOS/aerie/assets/40210944/bbcbbddd-9bef-481f-8c12-8cfdf157b16a)

The results of running just the GNC_DSS_Boresight_Vectors_Cal goal in isolation are:
![Screenshot 2023-08-03 at 10 14 36 AM](https://github.com/NASA-AMMOS/aerie/assets/40210944/2957a385-5a72-4e97-8769-c9725198f319)

Ideally, the way these goals are written and run together would result in the GNC_DSS_Boresight_Vectors_Cal goal's grouping of activities occurring _after_ the grouping relevant to the TEL_HGA_Cruise_Cal goal. This would look like two separate GNC_Single_Turn activities instead of the single turn instance that only satisfies the TEL_HGA_Cruise_Cal scheduling needs but not the GNC_DSS_Boresight_Vectors_Cal's. The below is a depiction of this ideal case - this was generated by shifting the applyWhen of the of GNC Generic anchor for the DSS Cal to ~4hrs after the >2AU transition (instead of the true constraint of just >2AU).

![Screenshot 2023-08-03 at 10 52 47 AM](https://github.com/NASA-AMMOS/aerie/assets/40210944/13082843-ed16-46e2-aa85-53ec01c659dd)

### Reproduction

This bug could be reproduced by testing two separate scheduling goals, each including:

1. The same activity with several parameters linked to occur _prior_ (via an endsAt the start of the anchor) to a main anchor activity type (from the example above this was GNC_Single_Turn). Ensure some of the parameters vary from one goal to the next.
2. The same activity with several parameters linked to occur _post_ (via a startsAt the end of the anchor) the main anchor activity type (from the example above this was GNC_Single_Turn). Ensure some of the parameters vary from one goal to the next.
3. The same applyWhen constraint window applied to the placement of the main anchor activities (from the example above: anchor activities Generic_GNC_Hardware_State_Update & TEL_HGA_Ka_Calibration with applyWhen -> Real.Resource("/geometry/spacecraftBodyRange_SUN").greaterThan(2*AU))

Ensure that each activity instance linked via coexistence goals as well as the main anchor have associated activityFinders included in the goal with all parameters specified.

Next, run the scheduling goals together and observe the results. Note if the activity type in between the main anchors only satisfies one of the two goal's parameter specifications.

It should be noted this showed up on the eurc adaptation using clipper-specific activity implementations. If it is not easy to replicate I can provide more details into the scheduling goals and activity types used.

### System Info

```shell
Google Chrome browser, macOS Ventura 13.3.1
```

### Severity

Moderate

### Workaround

Manually schedule activity

**Comment by adrienmaillard** [comment] 2024-02-28 19:40
Could not reproduce with integration test cases. Will try with original clipper goals.

**Comment by adrienmaillard** [comment] 2024-02-28 23:30
Reproduced the run with slightly modified activity templates (due to changes in the mission model), did not notice the same behavior.

**Comment by adrienmaillard** [comment] 2024-03-05 01:42
We looked at this with Megan. This is not a problem with the activity finder but with the greedy nature of our scheduling algorithm. 

In the following screenshot, the GNC_Single_Turn (aka A) is part of the first goal. It is placed at the end of the sequence. Then the second goal places a Generic_GNC_Hardware_State_Update (aka B) at the first available space after crossing the 2AU region and so it places it immediately after the set of activities from the first goal. Then, the second goal continues its execution and tries placing a GNC_Single_Turn (C) just before B (as one of the subgoal states). But it can't because there is a concurrent turn at the same spot, placed by the first goal. The goal then fails. 

This is a typical illustration of why we should have backtracking and why we should not schedule activities as greedily as we do. This is related to #870, #1073, and #1121. In this precise case, after inserting B and seeing that C cannot be inserted, we should backtrack, cut the domain of B so that C can be inserted and try again from there. 

![Screenshot 2024-03-04 at 5 35 56 PM](https://github.com/NASA-AMMOS/aerie/assets/94930916/93b6a0ee-05ff-46f3-812b-c329a52249c2)

**Comment by adrienmaillard** [comment] 2024-03-05 01:48
@dandelany I propose we close this ticket. I have mentioned it in other relevant tickets. This should be handled first by grouping (backtracking/reasoning at the group level) and then more generally with satisficing scheduling (backtracking/reasoning at the plan level).

**Closed as completed** 2024-03-05 21:42 UTC
Labels: bug, scheduling, clipper, next
