### ISSUE TITLE
Preset Value Entry Resulting in "Activity Preset Update Failed"

### ISSUE THREAD

**Issue by meganmjones** [NASA-AMMOS/aerie#1250] opened 2023-11-30 01:45 UTC
### Checked for duplicates

No - I haven't checked

### Is this a regression?

No - This is a new bug

### Version

1.14

### Describe the bug

Bug showing up when trying to create a preset by first saving a new preset after entering the name and _then_ going in and altering the parameters before saving as. This order causes a failed preset error. Only a specific order can be done when making presets for it to properly save.

### Reproduction

When adding a preset into the UI directly follow these steps to recreate:
1. Add in an activity type that has alterable parameters
2. Go to Selected Activity tab and in preset section, first enter a unique preset name & click the “Save as New Preset” plus button.
3. Now, alter one or several parameters in the activity to reflect what you want the preset to represent and click the “Save Changes” button

When following this sequence while trying to create presets the error "Activity Preset Update Failed" pops up in the lower left hand side of the UI. 

Workaround is adding a fresh default activity instance, going in and altering all the parameters _and_ preset name fields and _then_ clicking the “Save as New Preset” plus button. 

### System Info

```shell
Google Chrome browser, macOS Ventura 13.3.1
```

### Severity

Minor

**Comment by Mythicaeda** [comment] 2023-12-05 17:45
Duplicate of [Updating a Preset Fails](https://github.com/NASA-AMMOS/aerie-ui/issues/1018)

**Closed as not planned by Mythicaeda** 2023-12-05 17:45 UTC
Labels: bug
