### ISSUE TITLE
Set activity instance metadata through a scheduling profile

### ISSUE THREAD

**Issue by bashbash** [NASA-AMMOS/aerie#777] opened 2023-03-17 23:18 UTC
abercrom
https://jira.jpl.nasa.gov/browse/AERIEQS-373
Moderate
It would be useful to be able to set activity instance metadata through a scheduling profile, especially the activity instance name. This would allow a scheduling rule to assign a meaningful name to activity instances created by the scheduler.

**Comment by mattdailis** [comment] 2023-08-30 02:48
Duplicate of #756

**Closed as not planned by mattdailis** 2023-08-30 02:48 UTC
Labels: clipper
