### ISSUE TITLE
Data Type for "Number" Insufficient in Sequence Editor

### ISSUE THREAD

**Issue by dlconner** [NASA-AMMOS/aerie#737] opened 2023-03-14 21:52 UTC
Aerie Sequence Editor treats all numbers the same without regard to the actual number data type.  E.g. a float is not distinguished from an integer.  The JSON file is created without errors that will be caught by SEQGEN.   This should be caught in the editor as a bad data type.

**Comment by camargo** [comment] 2023-05-03 21:13
Duplicate of https://github.com/NASA-AMMOS/aerie/issues/743

**Closed as not planned by camargo** 2023-05-03 21:13 UTC
Labels: sequencing, clipper
