### ISSUE TITLE
Provide single GraphQL endpoint to get activity effective arguments

### ISSUE THREAD

**Issue by bashbash** [NASA-AMMOS/aerie#770] opened 2023-03-17 21:35 UTC
abercrom
https://jira.jpl.nasa.gov/browse/AERIEQS-399
Moderate
Clipper has several tools that need to interact with the Aerie plan. These tools need to download the plan, get all activities, and view/edit the activity parameter values. Currently this takes several steps because the plan query only includes overridden activity arguments, no the default values. The user needs to run one GraphQL query to download the plan, then a query to getActivityEffectiveArgumentsfor each activity in order to get the effective arguments. This puts a lot of work on the client for what is a very common use case. It would be useful to have a way to download the plan with activity effective arguments in one query.

**Comment by camargo** [comment] 2023-08-07 19:43
Duplicate of https://github.com/NASA-AMMOS/aerie/issues/666
Resolved in https://github.com/NASA-AMMOS/aerie/pull/984
CC @parkerabercrombie

**Closed as not planned by camargo** 2023-08-07 19:43 UTC
Labels: clipper
