### ISSUE TITLE
Express rolling window constraint in constraints eDSL

### ISSUE THREAD

**Issue by bashbash** [NASA-AMMOS/aerie#772] opened 2023-03-17 21:35 UTC
dailis
https://jira.jpl.nasa.gov/browse/AERIEQS-396
Moderate
The use case is a flight rule that states a piece of hardware can only be powered on for 200 minutes across any given 8 hour span.

So the existing lessThan node could flag any occurrence when it is powered on for more than 200 minutes at once, but I also need to catch cases like if its powered on for 120 minutes, off for 60, and then back on for 120

Reported by Sloan: [https://jpl.slack.com/archives/C0163E42UBF/p1666903380420049]

**Comment by camargo** [comment] 2023-08-07 19:45
Duplicate of https://github.com/NASA-AMMOS/aerie/issues/1015

**Closed as not planned by camargo** 2023-08-07 19:45 UTC
Labels: constraints, clipper
